# Generated by Django 4.1.7 on 2023-04-06 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
