# Generated by Django 4.1.7 on 2023-04-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_student_date_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.TextField()),
                ('Date_field', models.TextField()),
                ('morning_attendance', models.BooleanField(default=True)),
                ('afternoon_attendance', models.TextField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_field',
        ),
    ]
