# Generated by Django 4.1.7 on 2023-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_remove_student_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='College_Name',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
